# Generated by Django 3.1.2 on 2020-11-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='paciente_id',
            new_name='paciente',
        ),
    ]
