# Generated by Django 3.1.2 on 2020-11-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20201122_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
