# Generated by Django 3.1.2 on 2020-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201122_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
